import styled from "styled-components";
import Head from "next/head";
import Sidebar from "../../components/Sidebar";
import ChatScreen from "../../components/ChatScreen";
import { auth, db } from "../../firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import getRecipientEmail from "../../utils/getRecipientEmail";

function Chat({ chat, messages }) {
  // console.log(chat);
  // console.log(messages);
  const [user] = useAuthState(auth);

  return (
    <Container>
      <Head>
        <title>Chat | {getRecipientEmail(chat.users, user)}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />

      <ChatContanier>
        <ChatScreen chat={chat} messages={messages} />
      </ChatContanier>
    </Container>
  );
}

export default Chat;

// Server SIDE Rendered
export async function getServerSideProps(context) {
  const ref = db.collection("chats").doc(context.query.id);

  // PREP THE messages ON THE SERVER
  const messagesRes = await ref
    .collection("messages")
    .orderBy("timestamp", "asc")
    .get();

  const messages = messagesRes.docs
    .map((doc) => ({
      id: doc.id,
      ...doc.data(),
    }))
    .map((messages) => ({
      ...messages,
      timpestamp: messages.timestamp.toDate().getTime(),
    }));

  // PREP THE chats ON TEH SERVER
  const chatRes = await ref.get();
  const chat = {
    id: chatRes.id,
    ...chatRes.data(),
  };

  //   console.log(chat, messages);

  return {
    props: {
      messages: JSON.stringify(messages),
      chat: chat,
    },
  };
}

const Container = styled.div`
  display: flex;
  flex-direction: row;
  overflow: scroll;

  ::-webkit-scrollbar {
    display: none;
  }

  -ms-overflow-style: none;
  scrollbar-width: none;
`;

const ChatContanier = styled.div`
  flex: 1;
`;
